name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  initialize:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install xcodegen
      run: brew install xcodegen

    - name: Create Project Structure and Generate Xcode Project
      run: |
        mkdir -p fokusapp/Sources

        # Confirm directory creation
        if [ ! -d "fokusapp" ]; then
          echo "Error: Directory 'fokusapp' not created!"
          exit 1
        fi

        echo "name: fokusapp" > fokusapp/project.yml
        cat <<EOT >> fokusapp/project.yml
        options:
          bundleIdPrefix: com.example
          deploymentTarget: '13.0'
        targets:
          fokusapp:
            type: application
            platform: iOS
            sources: [Sources]
        EOT

        echo "import UIKit" > fokusapp/Sources/AppDelegate.swift
        echo "@UIApplicationMain" >> fokusapp/Sources/AppDelegate.swift
        echo "class AppDelegate: UIResponder, UIApplicationDelegate {" >> fokusapp/Sources/AppDelegate.swift
        echo "  var window: UIWindow?" >> fokusapp/Sources/AppDelegate.swift
        echo "  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {" >> fokusapp/Sources/AppDelegate.swift
        echo "    return true" >> fokusapp/Sources/AppDelegate.swift
        echo "  }" >> fokusapp/Sources/AppDelegate.swift
        echo "}" >> fokusapp/Sources/AppDelegate.swift

        xcodegen generate --spec fokusapp/project.yml --project-root fokusapp
      shell: bash

    - name: Verify Files and Directories
      run: |
        echo "Verifying 'fokusapp' directory contents before upload:"
        ls -R fokusapp || { echo "'fokusapp' directory not found!"; exit 1; }

    - name: Upload Project Directory
      uses: actions/upload-artifact@v3
      with:
        name: fokusapp
        path: fokusapp/

  build:
    runs-on: macos-latest
    needs: initialize

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Project Directory
      uses: actions/download-artifact@v3
      with:
        name: fokusapp

    - name: Debug Artifact Contents
      run: |
        echo "Verifying 'fokusapp' directory after download:"
        ls -R fokusapp || { echo "'fokusapp' directory not found after download!"; exit 1; }

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Initialize CocoaPods and Install Dependencies
      run: |
        cd fokusapp
        pod init
        pod install

    - name: Build app
      run: |
        cd fokusapp
        xcodebuild -workspace fokusapp.xcworkspace -scheme fokusapp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.5' build
